# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  hosts:
    - host: argo-test5.kube.pd.lan
      paths:
        - path: /
          pathType: ImplementationSpecific
