apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook3
  namespace: default
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - values-common.yaml
      - values-test3.yaml

